

FROM alpine:3.17 as build
RUN apk add --no-cache nodejs npm
WORKDIR /app
COPY public/ ./public/
COPY src/ ./src/
COPY index.html ./
COPY package*.json ./
COPY vite.config.js ./
RUN npm install
RUN npm run build

FROM nginx:1.24-alpine3.17
COPY --from=build /app/dist /var/www/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
