filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log

filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/mnt/nginx/access.log"]
  error:
    enabled: true
    var.paths: ["/mnt/nginx/error.log"]

- module: redis
  log:
    enabled: true
    var.paths: ["/mnt/redis/redis.log"]
  slowlog:
    enabled: true
    var.hosts: ["redis:6379"]

- module: postgresql
  log:
    enabled: true
    var.paths: ["/mnt/postgres/*.log"]

setup:
  dashboards.enabled: true
  kibana:
    host: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    ssl:
      certificate: "certs/filebeat/filebeat.crt"
      certificate_authorities: "certs/ca/ca.crt"
      key: "certs/filebeat/filebeat.key"

  template.settings:
    index.number_of_replicas: 0
  ilm:
    enabled: true
    policy_name: transcendence

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
