# Generated by Django 4.2.7 on 2023-12-06 12:48
# see https://docs.djangoproject.com/en/4.2/topics/migrations/#data-migrations

from django.db import migrations
from django.utils import timezone
import datetime

class Migration(migrations.Migration):

    def create_users(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        User = apps.get_model("api", "User")
        user_data = [{
                'name': "root",
                'fullname': "Root user",
                'created_at': datetime.datetime.now(tz=timezone.utc) 
                }]

        User.objects.create(**user_data[0])

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
