# Generated by Django 4.2.7 on 2024-01-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notification_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
