# Generated by Django 4.2.7 on 2024-01-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_nickname'),
        ('api', '0003_delete_notification'),
    ]

    operations = [
    ]
