# Generated by Django 4.2.7 on 2023-12-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friend_friend_alter_friend_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='user_id',
            new_name='player_id',
        ),
        migrations.AddField(
            model_name='match',
            name='player2_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='api.user'),
            preserve_default=False,
        ),
    ]
