# Generated by Django 4.2.7 on 2024-01-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_nickname'),
        ('api', '0004_merge_0002_user_nickname_0003_delete_notification'),
    ]

    operations = [
    ]
