# Generated by Django 4.2.7 on 2024-02-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tournament_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
