# Generated by Django 4.2.7 on 2024-02-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_nickname'),
        ('api', '0007_delete_userstats'),
    ]

    operations = [
    ]
