# Generated by Django 4.2.7 on 2024-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0002_remove_user_nickname_0007_delete_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
