# Generated by Django 4.2.7 on 2024-02-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_avatar'),
        ('api', '0009_user_nickname'),
    ]

    operations = [
    ]
