# Generated by Django 4.2.7 on 2024-02-09 12:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_0008_alter_user_avatar_0009_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.User.avatar_path),
        ),
    ]
