# Generated by Django 4.2.7 on 2024-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_avatar'),
    ]

    operations = [
     #   migrations.AddField(
     #       model_name='tournament',
     #       name='test',
     #       field=models.CharField(max_length=12, null=True, unique=True),
     #   ),
    ]
