# Generated by Django 4.2.7 on 2024-02-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tournament_test'),
        ('api', '0011_alter_user_avatar'),
    ]

    operations = [
    ]
