# Generated by Django 4.2.7 on 2024-02-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_0008_tournament_test_0011_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='test',
        ),
    ]
