# Generated by Django 4.2.7 on 2024-03-08 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_game_player1_score_alter_game_player2_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)]),
        ),
    ]
