# Generated by Django 4.2.7 on 2024-04-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_game_player1_score_alter_game_player2_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
    ]
