# Generated by Django 4.2.7 on 2024-04-16 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ranking',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
