# Generated by Django 4.2.7 on 2024-04-19 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tournament_ranking_alter_tournament_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')]),
        ),
    ]
