# Generated by Django 4.2.7 on 2024-04-19 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username too shot, must contain at least 3 characters')]),
        ),
    ]
