# Generated by Django 4.2.7 on 2024-04-20 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Title is too short, must contain at least 3 characters'), django.core.validators.RegexValidator('^[A-Za-z0-9? _-', message='Title should be a combination of alphanumeric characters, spaces and/or dashes')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username too short, must contain at least 3 characters'), django.core.validators.RegexValidator('^(\\w+\\d+|\\d+\\w+)+$', message='Username should be a combination of alphanumeric characters')]),
        ),
    ]
