# Generated by Django 4.2.7 on 2024-04-20 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_tournament_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Title is too short, must contain at least 3 characters'), django.core.validators.RegexValidator('^(\\w+)([\\w\\-_\\ ])+$', message='Title should be a combination of alphanumeric characters, spaces and/or dashes')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username too short, must contain at least 3 characters'), django.core.validators.RegexValidator('^([a-z]+)([\\w\\d]+)+$', message='Username should be a combination of alphanumeric characters')]),
        ),
    ]
