# Generated by Django 4.2.7 on 2024-04-20 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_tournament_title_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Nickname is too short, must contain at least 3 characters'), django.core.validators.RegexValidator('^([a-zA-Z]+)([\\w\\d\\s\\-_]+)+$', message='Nickname should be a combination of alphanumeric characters')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username too short, must contain at least 3 characters'), django.core.validators.RegexValidator('^[a-z]+$', message='Username should be a combination of low case letters')]),
        ),
    ]
